### ISSUE TITLE
Query: Secure Validation of DID-to-Domain Linkage

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/well-known#8]
In this [section](https://github.com/decentralized-identity/well-known/tree/master/did-configuration#secure-validation-of-did-to-domain-linkage) it speaks of a trusted browser based API being invoked to validate the QR content prior to display for scanning via the identity wallet. Because the scanning is still an extra step, shouldn't the Identity Wallet instead being doing this validation on the content decoded from the QR-Code, otherwise forged QR-Codes could still be generated in browser that simply bypass the usage of the trusted browser API?

**Comment by tplooker** [comment]
@csuwildcat tagging you as you might be able to clarify?

**Comment by csuwildcat** [comment]
The wallet app on a phone, a different device with no code context relationship awareness, cannot validate that the QR code it read is linked to the domain origin of the page. Only the browser that controls displaying can. Trusted UI is a type of presentation that a page cannot fake, due to use of browser 'chrome' (the parts of the browser, e.g. address bar, it has no access to). This trusted UI is what must gate the presentation, and only allow presentations via its mechanism after domain/DID linkage is confirmed. The identity wallet can only verify the payload it sees is signed by whatever DID the payload happens to contain, but has no understanding of the relationship between the payload and the origin that raised it in code.

**Comment by tplooker** [comment]
Thanks, granted, the wallet app cannot validate the QR code against the origin of the page that rendered it for reasons you described above, however it can still validate the QR codes content was signed by a DID and then discover that DIDs association to a domain.

A couple more questions on this
- What is there to prevent bypassing the usage of the trusted API and instead just rendering the QR code directly in the page? 
- Further more how would the wallet app scanning the QR code know it was validated by the browsers trusted API?

**Comment by csuwildcat** [comment]
1) There's nothing to prevent a page from trying to mimic trusted UI
appearances within the content viewport, but they never look the same as
what a browser can do - which is the point of a UI that exists outside the
reach of the page. This is what gates geolocation, camera access, and other
invocations.

2) It's not about the wallet validating the payload, which would happen
regardless, it's about communicating to the user that their UA has vetted
the invocation, and that there's no rogue script in the page invoking a
presentation of a random DID. This is a much higher barrier for various
attacks that would be far easier without requiring a strict confirmation
payload to exist on the domain, as a signed well-know resource implies.

**Comment by tplooker** [comment]
Ok cool I understand this now, thanks for the clarification.
