### ISSUE TITLE
Flesh out the addition of a `primary` flag to designate a main DID

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/well-known#9]
I have added the general concept to the spec, at the entry level, but we need to decide on a few things:

1. Do we recognize multiple `primary` references?
2. If we do not allow multiple references (my preference) how do we disregard multiple references present? I would argue we honor the one that is found first in a standard JSON parse/iteration of the object.
3. Do we need to include a reference both in the unsigned entry object and the inner JTW, to ensure primary is a protected declaration?

**Comment by OR13** [comment]
1 + 2: I think its best that we use a priority system (integer) vs boolean, and when duplicates exist the first one is chosen.

3. I think its best NOT to put the primary binding info in the token, because an admin may want to rotate primary, and would not be able to do so if the value were in the token. (consider dynamic loadbalancing, etc...)

**Comment by OR13** [comment]
I also think this concept should be explicit, building logic around the order of objects in JSON is a bad practice IMO, explicit object properties are prefered.

**Comment by csuwildcat** [comment]
Removed for now, addressed in latest commit: https://github.com/decentralized-identity/well-known/commit/eab39413b9b22548760255281fda80ecf38f074c
